version: '3.7'
name: ecommerce-batch-december2023
services:
  web:
    container_name: ecommerce-catalog
    build:
      context: ..
      dockerfile: docker/DockerFile
    ports:
    - '8085:8080'
    volumes:
    - '..:/app'